apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: db
data:
  POSTGRES_DB: chat
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: FinchDev
  # POSTGRES_MULTIPLE_DATABASES: "\"pact-broker\",\"chat\""